# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a04030d62c6e281f191fe258f35b1d034dadd3b342ad5032aa86961087f6a97caab753856c43fb705667e80a686fdbb2e3192751504c22a9a1d3f2dd3e620321

test:
  secret_key_base: 08787728de17003c19d1c72138848aed611fe85de3c4c242c1be09d58a70d53ba0f9970456410e98502047e3d0f336735305aa9d84824056d0ecaa5a54d6f56b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
